blank_issues_enabled: false
contact_links:
  - name: ‚ö†Ô∏è Problema da aplica√ß√£o
    url: https://github.com/mihonapp/mihon/issues/new/choose
    about: Problemas e solicita√ß√µes sobre o pr√≥prio aplicativo devem ser abertos no reposit√≥rio do Mihon
  - name: üì¶ Lista de extens√µes
    url: https://raw.githubusercontent.com/FelipeGFA/extensoes/repo/index.min.json
    about: Lista de todas as extens√µes dispon√≠veis com links de download
  - name: üñ•Ô∏è Site do Mihon
    url: https://mihon.app/docs/guides/troubleshooting/
    about: Guias, solu√ß√£o de problemas e respostas para perguntas comuns
