blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Application issue
    url: https://github.com/tachiyomiorg/tachiyomi/issues/new/choose
    about: Issues and requests about the app itself should be opened in the tachiyomi repository instead
  - name: ğŸ“¦ Tachiyomi official extensions
    url: https://tachiyomi.org/extensions
    about: List of all available official extensions with download links
  - name: ğŸ–¥ï¸ Tachiyomi website
    url: https://tachiyomi.org/help/
    about: Guides, troubleshooting, and answers to common questions
