name: "Batch close stale issues"

on:
  # Monthly
  schedule:
    - cron: '0 0 1 * *'
  # Manual trigger
  workflow_dispatch:
    inputs:


jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Close everything older than a year
          days-before-issue-stale: 365
          days-before-issue-close: 0
          exempt-issue-labels: "do-not-autoclose,Meta request"
          close-issue-message: "In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/keiyoushi/extensions-source/issues/new/choose)."
          close-issue-reason: not_planned
          ascending: true
          operations-per-run: 250
